name: Metrics
on: [push, pull_request]

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Executar testes
        run:  docker network create siged_backend && docker-compose run api_users bash -c  "yarn && yarn jest --coverage --outputFile=test-results.json --json --forceExit"

      - name: Coletar m√©tricas
        run: |
          python3 parser.py fga-eps-mds_${{ github.event.repository.name }}
          git config --global user.email "${{secrets.CI_EMAIL}}"
          git config --global user.name "${{secrets.CI_USERNAME}}"
          git pull
          git add *.json
          git commit -m "Generating sonarcloud metrics ${{github.event.repo_name}}"
          git push
          echo "Compile complete."